name: Deploy to QA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli --global

    - name: Authenticate to Salesforce
      run: |
        echo "${{ secrets.SF_PRIVATE_KEY }}" > server.key
        sfdx auth:jwt:grant --clientid ${{ secrets.SF_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SF_USERNAME }} --instanceurl ${{ secrets.SF_INSTANCE_URL }}
    
    - name: Deploy to QA Org
      run: |
        sfdx force:source:deploy -p force-app -u ${{ secrets.SF_USERNAME }} --wait 10 --checkonly
        sfdx force:source:deploy -p force-app -u ${{ secrets.SF_USERNAME }} --wait 10 --testlevel RunLocalTests
