name: Salesforce Delta Deploy Using JWT

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # 👈 needed so we can diff against main

    - name: Install Salesforce CLI and sfdx-git-delta
      run: |
        npm install --global @salesforce/cli
        sf plugins install sfdx-git-delta

    - name: Create server.key file
      run: |
        echo "${{ secrets.SF_JWT_KEY }}" > server.key

    - name: Authenticate with Salesforce (JWT)
      run: |
        sf org login jwt \
          --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
          --jwt-key-file server.key \
          --username "${{ secrets.SF_USERNAME }}" \
          --instance-url "${{ secrets.SF_INSTANCE_URL }}" \
          --alias jwt-org \
          --set-default

    - name: Create delta package with sfdx-git-delta
      run: |
        mkdir delta
        sf sgd:source:delta \
          --to "HEAD" \
          --from "origin/main" \
          --output delta \
          --ignore .forceignore

    - name: Deploy delta changes to Salesforce
      run: |
        if [ -f "delta/package/package.xml" ]; then
          echo "Deploying delta package..."
          sf project deploy start \
            --manifest delta/package/package.xml \
            --target-org jwt-org \
            --wait 10 \
            --test-level NoTestRun
        else
          echo "✅ No changes to deploy."
        fi
