name: Salesforce Delta Deploy Using JWT

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Salesforce CLI
      run: |
        npm install --global @salesforce/cli sfdx-git-delta

    - name: Create server.key file
      run: |
        echo "${{ secrets.SF_JWT_KEY }}" > server.key

    - name: Authenticate with Salesforce (JWT)
      run: |
        sf org login jwt \
          --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
          --jwt-key-file server.key \
          --username "${{ secrets.SF_USERNAME }}" \
          --instance-url "${{ secrets.SF_INSTANCE_URL }}" \
          --alias jwt-org \
          --set-default

    # 🔹 Generate delta package
    - name: Create delta package with sfdx-git-delta
      run: |
        mkdir delta
        npx sgd generate delta \
          --to "HEAD" \
          --from "origin/main" \
          --output delta \
          --ignore .forceignore

    # 🔹 Deploy only changed metadata
    - name: Deploy delta changes to Salesforce
      run: |
        if [ -d "delta/force-app" ]; then
          sf project deploy start \
            --source-dir delta/force-app \
            --manifest delta/package/package.xml \
            --target-org jwt-org \
            --wait 10 \
            --test-level NoTestRun
        else
          echo "No changes to deploy."
        fi
