name: Deploy to Salesforce on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: salesforcecli/github-action@v1

      - name: Authenticate to Salesforce
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --alias jwt-org \
            --instance-url https://login.salesforce.com

      - name: Deploy to Salesforce (No Tests)
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org jwt-org \
            --test-level NoTestRun \
            --wait 10
