name: Salesforce Delta Deploy Using JWT

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # full history so diff works

    - name: Install Salesforce CLI and sfdx-git-delta
      run: |
        npm install --global sfdx-cli
        sfdx plugins:install sfdx-git-delta

    - name: Debug changed files
      run: |
        echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
        echo "Head SHA: ${{ github.sha }}"
        echo "=== Changed files between base and head ==="
        git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.sha }}

    - name: Create server.key file
      run: |
        echo "${{ secrets.SF_JWT_KEY }}" > server.key

    - name: Authenticate with Salesforce (JWT)
      run: |
        sfdx force:auth:jwt:grant \
          --clientid "${{ secrets.SF_CONSUMER_KEY }}" \
          --jwtkeyfile server.key \
          --username "${{ secrets.SF_USERNAME }}" \
          --instanceurl "${{ secrets.SF_INSTANCE_URL }}" \
          --setdefaultusername \
          --setalias jwt-org

    - name: Create delta package with sfdx-git-delta
      run: |
        mkdir delta
        echo "Generating delta from ${{ github.event.pull_request.base.sha }} to HEAD"
        sfdx sgd:source:delta \
          --to HEAD \
          --from ${{ github.event.pull_request.base.sha }} \
          --output delta \
          --source force-app \
          --ignore .forceignore

    - name: Debug delta output
      run: |
        echo "=== Delta folder contents ==="
        ls -R delta || true
