name: Salesforce Delta Deploy Using JWT

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # full history needed for delta

    - name: Install SFDX CLI (classic) using official Action
      uses: salesforcecli/sfdx-action@v2
      with:
        version: latest

    - name: Install sfdx-git-delta plugin
      run: sfdx plugins:install sfdx-git-delta

    - name: Verify installed SFDX plugins
      run: sfdx plugins

    - name: Debug changed files
      run: |
        echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
        echo "Head SHA: ${{ github.sha }}"
        echo "=== Changed files between base and head ==="
        git diff --name-status ${{ github.event.pull_reques_
