name: Salesforce Deploy Using JWT

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-to-salesforce:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Needed so we can diff PR base vs head

    - name: Install Salesforce CLI
      run: |
        npm install --global @salesforce/cli

    - name: Create server.key file
      run: |
        echo "${{ secrets.SF_JWT_KEY }}" > server.key

    - name: Authenticate with Salesforce (JWT)
      run: |
        sf org login jwt \
          --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
          --jwt-key-file server.key \
          --username "${{ secrets.SF_USERNAME }}" \
          --instance-url "${{ secrets.SF_INSTANCE_URL }}" \
          --alias jwt-org \
          --set-default

    - name: Build delta folder
      run: |
        mkdir delta
        echo "Comparing commits..."
        git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt
        cat changed_files.txt

        while IFS= read -r file; do
          if [[ $file == force-app/* ]]; then
            echo "Copying $file into delta..."
            mkdir -p delta/$(dirname "$file")
            cp "$file" delta/"$file"
          fi
        done < changed_files.txt

        echo "Delta contents:"
        find delta

    - name: Deploy delta to Salesforce
      run: |
        if [ -d "delta/force-app" ]; then
          sf project deploy start --source-dir delta/force-app --target-org jwt-org --wait 10 --test-level NoTestRun
        else
          echo "No deployable changes detected."
        fi
