name: Salesforce Deploy Using JWT

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-to-salesforce:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # important so we can diff history

    - name: Install Salesforce CLI
      run: |
        npm install --global @salesforce/cli

    - name: Create server.key file
      run: |
        echo "${{ secrets.SF_JWT_KEY }}" > server.key

    - name: Authenticate with Salesforce (JWT)
      run: |
        sf org login jwt \
          --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
          --jwt-key-file server.key \
          --username "${{ secrets.SF_USERNAME }}" \
          --instance-url "${{ secrets.SF_INSTANCE_URL }}" \
          --alias jwt-org \
          --set-default

    - name: Find changed files in the merged PR
      id: diff
      run: |
        echo "PR base: ${{ github.event.pull_request.base.sha }}"
        echo "PR head: ${{ github.event.pull_request.head.sha }}"
        git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt
        cat changed_files.txt

    - name: Deploy only changed files
      run: |
        while IFS= read -r file; do
          if [[ $file == force-app/* ]]; then
            echo "Deploying $file ..."
            sf project deploy start --manifest $file --target-org jwt-org --wait 10 --test-level NoTestRun
          fi
        done < changed_files.txt
