name: Salesforce Deploy Using JWT

on:
  push:
    branches:
      - main

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Salesforce CLI
      run: |
        npm install --global @salesforce/cli

    - name: Create server.key file
      run: |
        echo "${{ secrets.SF_JWT_KEY }}" > server.key

    - name: Authenticate with Salesforce (JWT)
      run: |
        sf org login jwt \
          --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
          --jwt-key-file server.key \
          --username "${{ secrets.SF_USERNAME }}" \
          --instance-url "${{ secrets.SF_INSTANCE_URL }}" \
          --alias jwt-org \
          --set-default

    - name: Deploy source to org
      run: |
        sf project deploy start --source-dir force-app --target-org jwt-org --wait 10 --test-level RunLocalTests
