name: Salesforce Delta Deploy Using JWT

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # 👈 needed for git diff

    - name: Install Salesforce CLI and sfdx-git-delta
      run: |
        npm install --global sfdx-cli
        sfdx plugins:install sfdx-git-delta

    - name: Create server.key file
      run: |
        echo "${{ secrets.SF_JWT_KEY }}" > server.key

    - name: Authenticate with Salesforce (JWT)
      run: |
        sfdx force:auth:jwt:grant \
          --clientid "${{ secrets.SF_CONSUMER_KEY }}" \
          --jwtkeyfile server.key \
          --username "${{ secrets.SF_USERNAME }}" \
          --instanceurl "${{ secrets.SF_INSTANCE_URL }}" \
          --setdefaultusername \
          --setalias jwt-org

    - name: Create delta package with sfdx-git-delta
      run: |
        mkdir delta
        sfdx sgd:source:delta \
          --to "HEAD" \
          --from "origin/main" \
          --output delta \
          --ignore .forceignore

    - name: Deploy delta changes to Salesforce
      run: |
        if [ -f "delta/package/package.xml" ]; then
          echo "Deploying delta package..."
          sfdx force:source:deploy \
            --manifest delta/package/package.xml \
            --wait 10 \
            --testlevel NoTestRun
        else
          echo "✅ No changes to deploy."
        fi
